### ISSUE TITLE
Crashes on window resize

### ISSUE THREAD

**Issue by baryluk** [danilw/vulkan-shadertoy-launcher#1]
Works fine until you try to resize the window.

```
$ ./VK_shadertoy_launcher 
Init XCB

Not enough queues in the presentable queue family 0, used only one queue.
Couldn't acquire image
../vk_utils/vk_render_helper.c:105: Surface is out of date (VkResult -1000001004)
```

Linux 64-bit, Mesa 20.0.7, RADV (same with LLVM and ACO backends).

**Comment by danilw** [comment]
thanks for the bug report
Il back to code this project sometime later(weeks later), I do not have time and setup to test anything now

> Surface is out of date

I saw this problem even on Nvidia in Linux, on Nvidia it triggered randomly
I did not understand where it comes from, and for that moment I think its an X11 bug

I have AMD Vega8 integrated to test it, and will test when back to this project

**Comment by danilw** [comment]
I have fix it in https://github.com/danilw/vulkan-shadertoy-launcher/commit/6b55fff144f0f3feb3f1c86500cbf6f8a8664069

Tested on AMD in Linux it no longer crashes, so I close it.

Release not updated, will update with adding Wayland support next week.
